kind: Service
apiVersion: v1
metadata:
  name: database-api-svc
spec:
  type: NodePort
  ports:
  - name: database-api
    port: 6060
    nodePort: 30004
  selector:
    name: database-api
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: database-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: database-api
    spec:
      volumes:
      containers:
      - name: database-api-pod
        image: {{ DOCKER_IMAGE_PREFIX }}/database-api
        ports:
        - containerPort: 6060
          protocol: TCP
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      dnsPolicy: ClusterFirst
